version: "3.7"

volumes:
  mongodb_volume:
  logs:
      driver: local


services:

  parser:
    build: ./parser/
    restart: always
    environment:
       MONGO_HOST: mongodb
       MONGO_DATABASE: ${DATABASE}
       MONGO_COLLECTION: ${DATABASE_COLLECTION}
    links:
      - mongodb

  slim:
    build: ./news/
    restart: always
    working_dir: /news/var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
        docker: "true"
        MONGO_HOST: mongodb
        MONGO_DATABASE: ${DATABASE}
        MONGO_COLLECTION: ${DATABASE_COLLECTION}
    ports:
        - 8080:8080
    volumes:
        - ./news:/news/var/www
        - logs:/news/var/www/logs
    links:
        - composer
        - mongodb

  composer:
    image: composer
    restart: on-failure
    command: composer install --ignore-platform-reqs
    volumes:
    - ./news:/app
    working_dir: /app

  mongodb:
    image: mongo:latest
    restart: always
#    ports:
#    - 27017:27017
    volumes:
      - mongodb_volume:/data/db
