version: "3.7"

volumes:
  mongodb_volume:
    name: mongo
  logs:
      driver: local
      name: logs


services:

  parser:
    build: ./parser/
    restart: always
    environment:
       DOCKER: "true"
       MONGO_HOST: mongodb
       MONGO_DATABASE: ${DATABASE}
       MONGO_COLLECTION: ${DATABASE_COLLECTION}
    links:
      - mongodb
    container_name: news_parser

  slim:
    build: ./news/
    restart: always
    environment:
        docker: "true"
        MONGO_HOST: mongodb
        MONGO_DATABASE: ${DATABASE}
        MONGO_COLLECTION: ${DATABASE_COLLECTION}
    ports:
        - 8080:8000
    volumes:
        - ./news:/news/var/www
        - logs:/news/var/www/logs
    links:
        - mongodb
    container_name: news_site

  mongodb:
    image: mongo:latest
    restart: always
#    ports:
#      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    container_name: news_mongo
